AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  linebot-sam

  Sample SAM Template for linebot-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Parameters:
  ChannelSecret:
    Type: String
    NoEcho: true
    Description: LINE Channel secret (use real value in prod; for dev you can leave blank if reading from .env)
    Default: ""
  ChannelAccessToken:
    Type: String
    NoEcho: true
    Description: LINE Channel access token (use real value in prod; for dev you can leave blank if reading from .env)
    Default: ""

Resources:
  LineBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        ProcessMessage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          CHANNEL_SECRET: !Ref ChannelSecret
          CHANNEL_ACCESS_TOKEN: !Ref ChannelAccessToken

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LineBotApi:
    Description: API Gateway endpoint URL for Prod stage for Line Bot 
      function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LineBotFunction:
    Description: Line Bot Lambda Function ARN
    Value: !GetAtt LineBotFunction.Arn
  LineBotFunctionIamRole:
    Description: Implicit IAM Role created for Line Bot function
    Value: !GetAtt LineBotFunctionRole.Arn
